// <auto-generated />
using System;
using ImageHub.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImageHub.Migrations
{
    [DbContext(typeof(ImageHubDbContext))]
    partial class ImageHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ImageHub.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.Metadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Resources")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UploadAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Metadata", (string)null);
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.PublishJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublishTargetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PublishJob", (string)null);
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.PublishTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublishTargetType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PublishTarget", (string)null);

                    b.HasDiscriminator<string>("PublishTargetType").HasValue("PublishTarget");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resource", (string)null);
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Source", (string)null);

                    b.HasDiscriminator<string>("SourceType").HasValue("Source");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.TelegramGroupPublishTarget", b =>
                {
                    b.HasBaseType("ImageHub.Domain.Entities.PublishTarget");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("TelegramGroup");
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.PixivArtworksSource", b =>
                {
                    b.HasBaseType("ImageHub.Domain.Entities.Source");

                    b.Property<int>("Pid")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Pixiv");
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.TwitterTweetSource", b =>
                {
                    b.HasBaseType("ImageHub.Domain.Entities.Source");

                    b.Property<long>("TweetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Twitter");
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.WeiboBlogSource", b =>
                {
                    b.HasBaseType("ImageHub.Domain.Entities.Source");

                    b.Property<string>("BlogId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Weibo");
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.XiaoHongShuNoteSource", b =>
                {
                    b.HasBaseType("ImageHub.Domain.Entities.Source");

                    b.Property<string>("NoteId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("XsecToken")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("XiaoHongShu");
                });

            modelBuilder.Entity("ImageHub.Domain.Entities.Metadata", b =>
                {
                    b.HasOne("ImageHub.Domain.Entities.Source", null)
                        .WithOne()
                        .HasForeignKey("ImageHub.Domain.Entities.Metadata", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
