<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>MediaRelay</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MediaRelay.Abstractions\MediaRelay.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\" />
	  <Folder Include="Source\" />
	</ItemGroup>

</Project>
