<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\MediaRelay.Abstractions\MediaRelay.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Polly.Core" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="MediaRelay.Tests" />
		<InternalsVisibleTo Include="MediaRelay.Console.Logging" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Browser\Scripts\TwitterTweetVideoDownloadUrl.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Browser\Scripts\TwitterTweet.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
