<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<RootNamespace>MediaRelay</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Spectre.Console.Testing" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MediaRelay.Mock\MediaRelay.Mock.csproj" />
	</ItemGroup>

</Project>
