<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>MediaRelay</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Moq" />
		<PackageReference Include="Spectre.Console.Testing" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\MediaRelay.Console\MediaRelay.Console.csproj" />
	</ItemGroup>

</Project>
