<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<RootNamespace>MediaRelay</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\MediaRelay.Console\MediaRelay.Console.csproj" />
		<ProjectReference Include="..\..\src\MediaRelay.Immich\MediaRelay.Immich.csproj" />
		<ProjectReference Include="..\..\src\MediaRelay.Launcher\MediaRelay.Launcher.csproj" />
		<ProjectReference Include="..\..\src\MediaRelay.Pixiv\MediaRelay.Pixiv.csproj" />
		<ProjectReference Include="..\..\src\MediaRelay.Twitter\MediaRelay.Twitter.csproj" />
		<ProjectReference Include="..\..\src\MediaRelay\MediaRelay.csproj" />
		<ProjectReference Include="..\MediaRelay.Mock\MediaRelay.Mock.csproj" />
	</ItemGroup>

</Project>
