<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>MediaRelay</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Moq" />
		<PackageReference Include="Microsoft.Extensions.Logging" />
		<PackageReference Include="Microsoft.Extensions.Options" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\MediaRelay.Abstractions\MediaRelay.Abstractions.csproj" />
		<ProjectReference Include="..\..\src\MediaRelay.Url.Abstractions\MediaRelay.Url.Abstractions.csproj" />
	</ItemGroup>

</Project>
