<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
		<PackageReference Include="AsyncConsoleReader" />
		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="Spectre.Console.Json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\MediaRelay.Abstractions\MediaRelay.Abstractions.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="MediaRelay.Tests" />
	</ItemGroup>

</Project>
