<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AsyncConsoleReader" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
		<PackageReference Include="Microsoft.Extensions.Telemetry" />
		<PackageReference Include="Spectre.Console" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\MediaRelay.Twitter\MediaRelay.Twitter.csproj" />
		<ProjectReference Include="..\MediaRelay\MediaRelay.csproj" />
		<ProjectReference Include="..\MediaRelay.Immich\MediaRelay.Immich.csproj" />
		<ProjectReference Include="..\MediaRelay.Pixiv\MediaRelay.Pixiv.csproj" />
	</ItemGroup>


	<ItemGroup>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>


	<ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
