<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<UserSecretsId>5311a0ca-fb0e-452f-ba9c-dd10bb5c5b1b</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AsyncConsoleReader" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\MediaRelay\MediaRelay.csproj" />
		<ProjectReference Include="..\MediaRelay.Consol.Logging\MediaRelay.Console.Logging.csproj" />
		<ProjectReference Include="..\MediaRelay.Twitter\MediaRelay.Twitter.csproj" />
		<ProjectReference Include="..\MediaRelay.Immich\MediaRelay.Immich.csproj" />
		<ProjectReference Include="..\MediaRelay.Pixiv\MediaRelay.Pixiv.csproj" />
	</ItemGroup>


	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
